# Generated by Django 5.2.4 on 2025-07-30 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('INSPECTED', 'Inspected'), ('OUT_OF_SERVICE', 'Out of Service'), ('OUT_OF_ORDER', 'Out of Order')], default='INSPECTED', max_length=20)),
                ('occupancy_status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied')], default='VACANT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='hotels.room')),
            ],
            options={
                'ordering': ['room', '-status_date'],
                'unique_together': {('room', 'status_date')},
            },
        ),
    ]
